name: Run behave tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      with:
        python-version: '3.x'
    - name: Install python packages
      uses: actions/setup-python@v2
      run: python -m pip install behave pexpect
    - name: Run behave tests
      run: ./scripts/run_behave_tests.sh
